name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  push:
    branches:
      - main # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
